### ISSUE TITLE
Run the application locally

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/p2p-editor#1]
# 🤔 What

This will be the base feature in order to let us add further features in the next Milestones.

# 👤 User flow / UX

* [x] A user clones this repository
* [x] Run a Docker Compose in order to locally execute the web app (Example: localhost:8338)
* [x] The application generates a new document ID and redirects to it (Example: `localhost:8338/0d69a7c0-e04d-4ffd-9490-f4901a0bdeba`)
* [x] The user can share the unique ID and other users can access to the very same session through their local copy of the application

🚀 Use already available JS libraries in order to communicate using WebRTC or WebSockets. We could keep the high level abstraction by the moment in order to simplify the project bootstrap

# 💡 Centralized web apps used as inspiration

* http://3v4l.org
* https://scastie.scala-lang.org

**Comment by santakadev** [comment]
WebSocket is not an option for pure web implementation. It's not possible to create listening socket for incomming connections on the client side.

This leaves us with the following options:
a) Pure web implementation with WebRTC
b) Desktop implementation with browser for UI
c) Bundled implementation with electron

**Comment by santakadev** [comment]
ACE Code editor
https://github.com/ajaxorg/ace/

To write deltas to append only log while modifying the code https://ace.c9.io/#nav=api&api=editor

```javascript
editor.on('change', (delta) => {
    ...
})
```

To apply deltas comming from append only log https://stackoverflow.com/a/18905093

```javascript
editor.getSession().getDocument().applyDeltas(deltas);
```

**Comment by santakadev** [comment]
Working at chrome :tada: but failing at firefox :disappointed:

For testing:

1. clone the repository

2. run `docker-compose up`

3. Access http://localhost:8000. Get session id from chrome console:
```
chrome console
------------------------------------------------------------------
c7b4afba081293c4fb241451324fec0bbefc3b2107a460bf86af9c70021036dc
```

4. To let other people join the session, share the session id with them. They can join the session going to http://localhost:8000/#SESSION_ID
```
http://localhost:8000/#c7b4afba081293c4fb241451324fec0bbefc3b2107a460bf86af9c70021036dc
```

When someone is connected you will see in the console "new peer"
```
chrome console
------------------------------------------------------------------
new peer
```

That's all. Happy P2P coding :)

**Comment by JavierCane** [comment]
Good work!
