### ISSUE TITLE
Don't allow to modify caret position while on read only mode

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/p2p-editor#12]
# How to reproduce

1. User A opens a new session
2. User B joins the session and starts seeing how A type and following his/her careet
3. B makes a click moving out the caret to another position
4. A continue typing and moving out the caret
5. B continues to see the new text modifications but s/he has missed the caret position of A

# What would be expected

* Ideally, the user B would recover the caret position once user A makes a modification after B has modified the caret position (4)
* However, as a quick solution, we could make user B (and any other read only users) unable to set a new caret position

**Comment by santakadev** [comment]
This could help to solve the issue [editor.gotoLine](https://ace.c9.io/api/editor.html#Editor.gotoLine)

**Comment by JavierCane** [comment]
Please, deploy it on the test server in order to review it 🙏🙌

**Comment by santakadev** [comment]
Ready for review on test server
