### ISSUE TITLE
Standardize workflow

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/p2p-editor#14]
# Context

The application is gaining traction in terms of stabilizing the codebase and we're close to the 1.0 milestone. Congrats! 😬🙌

Because of that, I think we should do something in order to avoid losing the trace between issues and their corresponding changeset (Example: [issue](https://github.com/CodelyTV/p2p-editor/issues/10) - [changes](https://github.com/CodelyTV/p2p-editor/commit/e089b98ec99361fad7845a443ee94b9cc33cfb46)) 👼

# Why not to apply a classic PRs workflow yet

I understand that we're still in a very early stage of the application and we need to bootstrap the skeleton modifying a lot of times the very same lines of code.

If we apply a classic Pull Requests workflow (waiting for PR review and so on), we could make the experience a bit frustrating:

* Conflicts: Having to wait until a PR is merged in order to have the modifications available so we avoid conflicts because of modifying the same code
* Incremental changes: We wouldn't have the previous PR changes in order to develop further features based on that one.

Even if we could workaround that, for instance, concatenating PRs opening them based on the previous one; it could end up also being frustrating because of requesting changes on the first PR of the chain would make to apply it rebasing or merging all the concatenated PRs branches.

# Proposal

For this reason, I would suggest to open a PR per issue even if we don't block the PR merge. That is, we wouldn't have to wait for a PR approval in order to merge it.

This way we'll only modify `master` through PRs merge commits (not pushing commits directly to it). That leads to exposing the different changes we're making (so anyone can actually see _why_ we're making those changes), and be able to trace _when_ and _how_ an issue has been solved.

Furthermore, we'll allow to let anyone review the change set made due to a specific issue and provide feedback even if it has already been merged.

What do you think?

**Comment by santakadev** [comment]
This morning I was thinking about this same issue. As you said, work with classic PR workflow can be tedious / frustrating.

So, with the resources we have right now, I'm agree with your proposal.

We can review later the workflow if we start recieving contributions.

**Comment by JavierCane** [comment]
Nice to agree on this 😊

I'll close this issue then. Based on what you said, we'll operate with the following criteria:

* PR by a maintainer => Direct merge (by the moment)
* PR by a contributor => Review by a maintainer
