### ISSUE TITLE
Improve ReadMe

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/p2p-editor#4]
# `README.md` sections (`##`)

* [ ] 📜 Table of Contents
* [ ] 💡 What does P2P Editor do?
* [ ] 🤔 Why P2P?
* [ ] 🏗️ Architecture
    * [ ] Communications (Swarm & WebRTC)
    * [ ] Append only DB (Hypercore & Merkel Tree)
    * [ ] Storage (RAM)
    * [ ] Signalhub (Distribute connections)
    * [ ] Ace (Editor)
* [ ] 🚀 Environment setup
    * [ ] 🐳 Docker environment
    * [ ] ✅ Run the tests
* [ ] ℹ️ About
* [ ] 🤝 Contributing
* [ ] ⚖️ License

# Inspiration

* [🎯🐘 Hexagonal Architecture, DDD & CQRS in PHP Symfony](https://github.com/CodelyTV/cqrs-ddd-php-example/blob/master/README.md)
* [🚀 CodelyTV dotfiles](https://github.com/CodelyTV/dotfiles/blob/master/README.md)

**Comment by JavierCane** [comment]
Hi!

We've improved the standard `README.md` files structure making it mobile friendly. [Here you have an example](https://github.com/CodelyTV/cqrs-ddd-php-example/blob/master/README.md).

Hope it helps on the `README.md` bootstrapping 😊🚀

**Comment by santakadev** [comment]
Sketch of p2p editor architecture
![p2p-editor-architecture](https://user-images.githubusercontent.com/3189335/52896689-7d310f00-31cb-11e9-90c8-8a493d987137.jpg)

**Comment by JavierCane** [comment]
It would be awesome to include this picture inside some `assets/` folder as `architecture_diagram.jpg` or whatever, and embed it from the `README.md` in the PR: https://github.com/CodelyTV/p2p-editor/pull/18

If you want to polish it a bit, you can use a https://www.draw.io diagram, but this is optional and can be a further step 🙂
