### ISSUE TITLE
Fix security vulnerabilities

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/p2p-editor#46]
He have several [dependencies with known security vulnerabilities](https://github.com/CodelyTV/p2p-editor/network/alerts).

Would require the dependencies upgrade process modifications on our end due to public API changes? Or would it be something painless? 👼

**Comment by santakadev** [comment]
> He have several dependencies with known security vulnerabilities.

The link is broken or I'm not allowed to see its content. 😬

**Comment by JavierCane** [comment]
Sorry, I didn't noticed that security settings had its own privileges section. Now you should be able to see them 🤟

**Comment by santakadev** [comment]
I've fixed security vulnerabilities.
